### ISSUE TITLE
The 'pip3 install requirements.txt' command missing the '-r' option

### ISSUE THREAD

**Issue by ThomasMboto** [iamvucms/ImageClassifyAPI#5]
The `pip3 install requirements.txt` command noted in the installation steps should include the '-r' option. So it should be `pip3 install -r requirements.txt`. Without it, the following error will be logged:

![Screen Shot 2020-11-28 at 6 56 01 PM](https://user-images.githubusercontent.com/13873611/100528533-06041980-31ac-11eb-81e2-a1d45255d78c.png)

**Comment by iamvucms** [comment]
Hi, 
I'm just a newbie in python
Thank you very much for contributing.
